### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by dksheffield** [maciejtreder/angular-universal-serverless#5]
Output said to let you know, here is my debug log - any help would be appreciated! Thanks!!!

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-universal-serverless@1.0.0~prestart: angular-universal-serverless@1.0.0
6 silly lifecycle angular-universal-serverless@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-universal-serverless@1.0.0~start: angular-universal-serverless@1.0.0
8 verbose lifecycle angular-universal-serverless@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-universal-serverless@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/workspace/angular-universal-serverless/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
10 verbose lifecycle angular-universal-serverless@1.0.0~start: CWD: /home/ec2-user/workspace/angular-universal-serverless
11 silly lifecycle angular-universal-serverless@1.0.0~start: Args: [ '-c', 'npm run build && npm run server' ]
12 silly lifecycle angular-universal-serverless@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular-universal-serverless@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular-universal-serverless@1.0.0 start: `npm run build && npm run server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-universal-serverless@1.0.0
16 verbose cwd /home/ec2-user/workspace/angular-universal-serverless
17 error Linux 4.9.27-14.31.amzn1.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular-universal-serverless@1.0.0 start: `npm run build && npm run server`
22 error Exit status 1
23 error Failed at the angular-universal-serverless@1.0.0 start script 'npm run build && npm run server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-universal-serverless package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && npm run server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-universal-serverless
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-universal-serverless
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by maciejtreder** [comment]
Thank you for your report. Could you confirm if now it is working?

**Comment by dksheffield** [comment]
Gets to the webpack section on npm start then I get errors again - I did the following just to see:

- npm install -g @angular/cli
- npm install -g typescript
- npm install -g webpack

Here is my debug file this time:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-universal-serverless@1.0.0~prestart: angular-universal-serverless@1.0.0
6 silly lifecycle angular-universal-serverless@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-universal-serverless@1.0.0~start: angular-universal-serverless@1.0.0
8 verbose lifecycle angular-universal-serverless@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-universal-serverless@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/workspace/angular-universal-serverless/node_modules/.bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/home/ec2-user/.npm-global/bin
10 verbose lifecycle angular-universal-serverless@1.0.0~start: CWD: /home/ec2-user/workspace/angular-universal-serverless
11 silly lifecycle angular-universal-serverless@1.0.0~start: Args: [ '-c', 'npm run build && npm run server' ]
12 silly lifecycle angular-universal-serverless@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular-universal-serverless@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular-universal-serverless@1.0.0 start: `npm run build && npm run server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-universal-serverless@1.0.0
16 verbose cwd /home/ec2-user/workspace/angular-universal-serverless
17 error Linux 4.9.27-14.31.amzn1.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular-universal-serverless@1.0.0 start: `npm run build && npm run server`
22 error Exit status 1
23 error Failed at the angular-universal-serverless@1.0.0 start script 'npm run build && npm run server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-universal-serverless package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && npm run server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-universal-serverless
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-universal-serverless
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm going to go to stock angular universal and see if I can get that working and see if it sheds some light. Let me know if there is something else I can try for your repo. Thanks!

**Comment by maciejtreder** [comment]
Does webpack section run correctly? Could you check 'npm run build'? If it will fail, please provide whole console output (staring from line with command).

**Comment by dksheffield** [comment]
Here is my entire CLI output, im very familiar with angular and aws, but this is my first try at angular universal. I'm actually having trouble with vanilla angular universal too so any help would be appreciated. I'm assuming my dev machine is missing something... Thanks!

```
[ec2-user@ip-10-0-0-41 workspace]$ git clone https://github.com/maciejtreder/angular-universal-serverless.git
Cloning into 'angular-universal-serverless'...
remote: Counting objects: 262, done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 262 (delta 136), reused 255 (delta 129), pack-reused 0
Receiving objects: 100% (262/262), 675.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (136/136), done.
Checking connectivity... done.
[ec2-user@ip-10-0-0-41 workspace]$ cd angular-universal-serverless
[ec2-user@ip-10-0-0-41 angular-universal-serverless]$ PATH=$PATH:/usr/local/bin:~/.npm-global/bin
[ec2-user@ip-10-0-0-41 angular-universal-serverless]$ npm install
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
npm WARN prefer global ts-node@3.1.0 should be installed with -g

> node-sass@4.5.3 install /home/ec2-user/workspace/angular-universal-serverless/node_modules/node-sass
> node scripts/install.js



[ec2-user@ip-10-0-0-41 angular-universal-serverless]$ npm start

> angular-universal-serverless@1.0.0 start /home/ec2-user/workspace/angular-universal-serverless
> npm run build && npm run server


> angular-universal-serverless@1.0.0 prebuild /home/ec2-user/workspace/angular-universal-serverless
> npm run clean


> angular-universal-serverless@1.0.0 clean /home/ec2-user/workspace/angular-universal-serverless
> rimraf dist


> angular-universal-serverless@1.0.0 build /home/ec2-user/workspace/angular-universal-serverless
> webpack

sh: line 1:  2734 Killed                  npm run build

npm ERR! Linux 4.9.27-14.31.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-universal-serverless@1.0.0 start: `npm run build && npm run server`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the angular-universal-serverless@1.0.0 start script 'npm run build && npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-universal-serverless package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-universal-serverless
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-universal-serverless
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/workspace/angular-universal-serverless/npm-debug.log
[ec2-user@ip-10-0-0-41 angular-universal-serverless]$ npm run build

> angular-universal-serverless@1.0.0 prebuild /home/ec2-user/workspace/angular-universal-serverless
> npm run clean


> angular-universal-serverless@1.0.0 clean /home/ec2-user/workspace/angular-universal-serverless
> rimraf dist


> angular-universal-serverless@1.0.0 build /home/ec2-user/workspace/angular-universal-serverless
> webpack

Killed
[ec2-user@ip-10-0-0-41 angular-universal-serverless]$ 
```
